import React from "react";
import Head from "next/head";
import { axiosClient } from "../../libraries/axiosClient";

export default function Test({ categories }) {
  return (
    <>
      <Head>
        <title>Categories</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="Sản phẩm của chúng tôi" />
        <link rel="icon" href="/cloud-market.jpg" />
      </Head>
      <h1>Categories</h1>
      {categories &&
        categories.map((category) => {
          return (
            <div key={category._id}>
              <h4>{category.name}</h4>
              <h4>{category._id}</h4>
            </div>
          );
        })}
    </>
  );
}

export async function getStaticProps(context) {
  const dataCategories = await axiosClient.get("/categories");
  return {
    props: {
      categories: dataCategories,
    }, // will be passed to the page component as props
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  };
}
